apply plugin: "java-library"

java { sourceCompatibility = JavaVersion.VERSION_1_8; targetCompatibility = JavaVersion.VERSION_1_8 }
sourceSets 
{
    main 
    {
        java 
        {
            srcDir 'src'   
        }
    }
}

eclipse.project {
    name = appName + "-editor"
}

project.ext.mainClassName = "jks.launcher.Launcher_Game"

