apply plugin: "java"

sourceCompatibility = 1.8
sourceSets 
{
    main 
    {
        java 
        {
            srcDir 'src'
            srcDir 'assets'     
        }
    }
}

eclipse.project {
    name = appName + "-desktop"
}

project.ext.mainClassName = "jks.launcher.Launcher_Game"
project.ext.assetsDir = new File("../desktop/assets")
